name: CI
run-name: ${{ github.actor }} builds a wheel
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_BOT_NAME: github-actions[bot]
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get install --assume-yes python3-build python3-wheel python3-hatchling python3-hatch-vcs
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build wheel
        run: |
          python -m build --wheel --no-isolation
          pwd
          ls ${{ github.workspace }}
          python -m build --version
          python -m wheel version
          python -m hatchling version
          echo "A redacted token is: ${{ secrets.GITHUB_TOKEN }}"
      - name: Print status
        run: |
          echo "This job's status is ${{ job.status }}."
